"""Reads protobuf-encoded Position messages from a zmq SUB socket."""

from __future__ import annotations

import logging
from collections.abc import Iterator

import zmq

from trackerapp.ingest.base import SourceReader
from trackerapp.models.types import GeodeticPosition

# Generated by scripts/generate_proto.sh from proto/position.proto.
# Kept as a lazy import so the rest of the package imports cleanly before
# the proto bindings have been generated.
try:
    from trackerapp.proto_gen import position_pb2
except ImportError:  # pragma: no cover - only hit before codegen has run
    position_pb2 = None

logger = logging.getLogger(__name__)


class ZmqPositionReader(SourceReader):
    """Subscribes to a zmq PUB endpoint and decodes Position protobuf messages."""

    def __init__(self, endpoint: str, topic: str = "") -> None:
        if position_pb2 is None:
            raise RuntimeError(
                "position_pb2 not found - run scripts/generate_proto.sh first"
            )
        self._context = zmq.Context.instance()
        self._socket = self._context.socket(zmq.SUB)
        self._socket.connect(endpoint)
        self._socket.setsockopt_string(zmq.SUBSCRIBE, topic)
        self._endpoint = endpoint
        logger.info("subscribed to %s (topic=%r)", endpoint, topic)

    def __iter__(self) -> Iterator[GeodeticPosition]:
        while True:
            raw = self._socket.recv()
            msg = position_pb2.Position()
            msg.ParseFromString(raw)
            yield GeodeticPosition(
                track_id=msg.track_id,
                latitude_deg=msg.latitude_deg,
                longitude_deg=msg.longitude_deg,
                altitude_m=msg.altitude_m,
                timestamp=msg.timestamp,
            )

    def close(self) -> None:
        self._socket.close()
